CREATE TABLE services (
    service_id INT PRIMARY KEY,
    service_name VARCHAR(50),
    description VARCHAR(500),
    img_link VARCHAR(300)
);

INSERT INTO services (service_name, description, img_link) VALUES 
("Contract Documents", "Legal contracts serve as the backbone of countless business and personal transactions, providing a formal framework for defining rights, obligations, and responsibilities between parties involved. ", "https://res.cloudinary.com/dgi53xxbd/image/upload/v1694875757/sih_legal_docs/contract_img_ync08t.jpg"), 
("Trademark & Copyright Documents", "A trademark is a word or a visual symbol used by a business to differentiate its goods or services from those of other businesses that offer similar goods or services. A copyright is a right given to the creators of literary, musical, dramatic, artistic works, and the producers of cinematograph films and sound recordings. ", "https://res.cloudinary.com/dgi53xxbd/image/upload/v1694875997/sih_legal_docs/tm_copyright_img_hd7o0e.jpg"), 
("Banking/Finance Documents", "In India, the banking and finance sector operates under a comprehensive legal framework that governs various aspects of financial services, institutions, and transactions. These laws are essential to ensure the stability, transparency, and integrity of the financial system.", "https://res.cloudinary.com/dgi53xxbd/image/upload/v1694876340/sih_legal_docs/banking_img_lcll8x.jpg"), 
("Property Documents", "Legal property refers to the bundle of rights and interests that a person or entity has in a physical or tangible asset, typically real estate or personal property. These rights are legally recognized and protected by the government and include the right to possess, use, control, enjoy, and dispose of the property. ", "https://res.cloudinary.com/dyxnmjtrg/image/upload/v1694691119/property_wb2bha.jpg"), 
("Bonds Documents", "Legal bonds are financial instruments that represent a debt obligation between the issuer, typically a government or corporation, and the bondholder, who lends money to the issuer in exchange for periodic interest payments and the return of the bond's face value at maturity. ", "https://res.cloudinary.com/dgi53xxbd/image/upload/v1694876804/sih_legal_docs/bonds_img_falmr0.jpg"), 
("Criminal Documents", "Legal criminal laws, also known as penal or criminal laws, form the foundation of a country's legal system, defining the boundaries of acceptable conduct and specifying the consequences for violating those boundaries", "https://res.cloudinary.com/dgi53xxbd/image/upload/v1694876933/sih_legal_docs/criminal_law_img_lt34dq.jpg"),
("Divorce/Family Documents", "Legal divorce is a formal legal process that dissolves a marriage or civil partnership, allowing spouses or partners to legally separate and end their marital obligations. It is an important aspect of family law, and the specifics of divorce proceedings can vary significantly from one jurisdiction to another", "https://res.cloudinary.com/dyxnmjtrg/image/upload/v1694753486/law_f6g4co.jpg");